name: Build Production

on: [push]

jobs:
  build_and_test:
    # Use ubuntu-20.04 LTS.
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: npm install and build
        run: |
          npm install
          npm run build --if-present
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build packing
          path: build
